[colors]
[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

# Normal colors
[colors.normal]
black = '#1e1e2e'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#cba6f7'
cyan = '#89dceb'
white = '#cdd6f4'

# Bright colors
[colors.bright]
black = '#585b70'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#cba6f7'
cyan = '#89dceb'
white = '#cdd6f4'

[colors.selection]
background = '#313244'
